brew "exa"
brew "direnv"
brew "git-cola"
brew "sphinx-doc" # required by git-cola
cask "github"
cask "google-chrome"
cask "alfred"
cask "bitwarden"
cask "firefox"
cask "gpg-suite"
cask "iterm2"
cask "jetbrains-toolbox"
cask "spectacle"
cask "standard-notes"
cask "telegram-desktop"
cask "visual-studio-code"
