tap "coursier/formulas"

brew "bat"
brew "coreutils" # grealpath
brew "coursier/formulas/coursier"
brew "curl"
brew "direnv"
brew "exa"
brew "exiftool"
brew "fasd"
brew "ghq"
brew "git-cola"
brew "jq"
brew "jenv"
brew "midnight-commander"
brew "node"
brew "osx-cpu-temp"
brew "pyenv"
brew "rsync"
brew "sphinx-doc" # required by git-cola
brew "the_silver_searcher"
brew "tig"
brew "tree"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "gpg-suite"
cask "iterm2"
cask "jetbrains-toolbox"
cask "obsidian"
cask "shottr"
cask "the-unarchiver"
cask "visual-studio-code"

