#!/bin/bash

set -e
set -x

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  if [ ! -f "$HOME/.iterm2_shell_integration.zsh" ]; then
    curl -L https://iterm2.com/shell_integration/zsh \
      -o ~/.iterm2_shell_integration.zsh
  fi

  if [[ $(sysctl -n machdep.cpu.brand_string) =~ "Apple" ]]; then
    softwareupdate --install-rosetta --agree-to-license
  fi

elif [ "$system_type" = "Linux" ]; then
  
  if ! command -v zsh >/dev/null 2>&1; then
    echo 'Install zsh first'
    exit 1
  fi

  sudo apt-get update
  sudo apt-get install -y \
    fasd \
    python3-pip \
    curl \
    wget \
    jq \
    tree \
    silversearcher-ag \
    bat \
    direnv

  if ! command -v jenv >/dev/null 2>&1; then
    echo "Installing jenv"
    git clone https://github.com/jenv/jenv.git ~/.jenv
  fi

  # Install Coursier if not available
  if ! command -v cs >/dev/null 2>&1; then
    echo "Installing Coursier"
    mkdir -p "$HOME/.local/bin"
    
    curl -fLo cs https://github.com/coursier/coursier/releases/latest/download/cs-x86_64-pc-linux.gz
    gzip -d cs
    chmod +x cs
    mv cs "$HOME/.local/bin/"
    
    export PATH="$HOME/.local/bin:$PATH"
  fi

fi

if [ ! -f "$HOME/.oh-my-zsh/README.md" ]; then
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

powerlevel10k_dir=${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
if [ ! -d $powerlevel10k_dir ]; then
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $powerlevel10k_dir
else
  git -C $powerlevel10k_dir pull --ff-only
fi

zsh_aliases_exa_dir=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-aliases-exa
if [ ! -f $zsh_aliases_exa_dir/zsh-aliases-exa.plugin.zsh ]; then
  git clone --no-checkout https://github.com/DarrinTisdale/zsh-aliases-exa.git $zsh_aliases_exa_dir
  git -c advice.detachedHead=false -C $zsh_aliases_exa_dir checkout f6b72da193f03911009cb95e3e2e18e48b918833
fi

cs java-home --jvm 19 | xargs jenv add
cs java-home --jvm 11 | xargs jenv add
cs install scala-cli
cs install coursier
cs install scala
cs install scalac
cs install sbt
cs install giter8
cs install scala3
cs install scalafix
cs install --contrib plantuml

if [ ! -d $(pyenv root)/versions/2.7.18 ]; then
  pyenv install 2.7.18
fi

pipx install cfv toms

NPM_PACKAGES_DIR="${HOME}/.npm-packages"
[ -d "$NPM_PACKAGES_DIR" ] || mkdir "$NPM_PACKAGES_DIR"

